# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74188c7dc82815e06dca3285e1fce44b2cf8dc415831fb056946a5302622007d1ce7d58dc8da9a8b898d4010713bb9a44a7bea661a6483e3f3f5a72b94ecda56

test:
  secret_key_base: 4d9bbc7d98b2f0eafad6f8ac06eb1b52f940ac0660752fa984751282e1c4b091e515beb42e291c05a1045979af66e0a123169a6e6959c5f11c5861dea2b44fef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
